name: build

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */12 * * *"

  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

concurrency:
  group: documentation-build
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Clone flarum/framework
        run: git clone https://github.com/flarum/framework.git flarum

      - name: PHP > Use PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: PHP > Doctum cache
        uses: actions/cache@v3
        with:
          path: cache
          key: ${{ runner.os }}-doctum

      - name: JS > Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: JS > Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build documentation
        run: |
          python scripts/build-js.py
          python scripts/build-php.py

      - name: Commit and push documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          if [ "$(git status --porcelain docs | wc -l)" -lt "2" ]; then
            echo "No changes to commit"
            git reset
            git checkout -- .
          else
            git commit -m "docs: update (flarum/framework@${FLARUM_SHA})" docs
          fi

      - name: Pull
        run: git pull --rebase

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}